#!/usr/bin/env python3
# KeelShim - Windows 7 user-mode UI translation for the Windows 10 kernel
# Copyright (C) 2026 Kevin Dalli <projectkeel@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import os
import sys
import pefile

OVERRIDES = {"DCompositionCreateDevice", "DCompositionCreateDevice2", "DCompositionCreateDevice3"}

NOTICE = """/*
 * KeelShim - Windows 7 user-mode UI translation for the Windows 10 kernel
 * Copyright (C) 2026 Kevin Dalli <projectkeel@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
""".splitlines()

src, outdir = sys.argv[1:3]
os.makedirs(outdir, exist_ok=True)

pe = pefile.PE(src, fast_load=True)
pe.parse_data_directories(directories=[pefile.DIRECTORY_ENTRY["IMAGE_DIRECTORY_ENTRY_EXPORT"]])

lines = NOTICE + [
    "",
    "// generated by tools/census/gen_dcomp_seam.py !do not edit!",
    "#pragma once",
]
named = forwarded = noname = 0
for e in sorted(pe.DIRECTORY_ENTRY_EXPORT.symbols, key=lambda s: s.ordinal):
    if not (e.address or e.forwarder):
        continue
    name = e.name.decode("ascii") if e.name else None
    if name and name in OVERRIDES:
        lines.append('#pragma comment(linker, "/EXPORT:%s,@%d")' % (name, e.ordinal))
        named += 1
    elif name:
        lines.append('#pragma comment(linker, "/EXPORT:%s=dcomp10.%s,@%d")' % (name, name, e.ordinal))
        forwarded += 1
    else:
        lines.append('#pragma comment(linker, "/EXPORT:ord%d=dcomp10.#%d,@%d,NONAME")'
                     % (e.ordinal, e.ordinal, e.ordinal))
        noname += 1
pe.close()

out = os.path.join(outdir, "exports.h")
with open(out, "w", newline="\r\n") as f:
    f.write("\n".join(lines) + "\n")
print("%s has %d implemented, %d forwarded by name, %d forwarded by ordinal (NONAME)"
      % (out, named, forwarded, noname))
