/*
 * KeelShim - Windows 7 user-mode UI translation for the Windows 10 kernel
 * Copyright (C) 2026 Kevin Dalli <projectkeel@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// generated by tools/census/gen_dcomp_seam.py !do not edit!
#pragma once
#pragma comment(linker, "/EXPORT:DCompositionAttachMouseDragToHwnd=dcomp10.DCompositionAttachMouseDragToHwnd,@1017")
#pragma comment(linker, "/EXPORT:DCompositionAttachMouseWheelToHwnd=dcomp10.DCompositionAttachMouseWheelToHwnd,@1018")
#pragma comment(linker, "/EXPORT:ord1019=dcomp10.#1019,@1019,NONAME")
#pragma comment(linker, "/EXPORT:DCompositionCreateDevice,@1020")
#pragma comment(linker, "/EXPORT:DCompositionCreateDevice2,@1021")
#pragma comment(linker, "/EXPORT:DCompositionCreateDevice3,@1022")
#pragma comment(linker, "/EXPORT:DCompositionCreateSurfaceHandle=dcomp10.DCompositionCreateSurfaceHandle,@1023")
#pragma comment(linker, "/EXPORT:DllCanUnloadNow=dcomp10.DllCanUnloadNow,@1024")
#pragma comment(linker, "/EXPORT:DllGetActivationFactory=dcomp10.DllGetActivationFactory,@1025")
#pragma comment(linker, "/EXPORT:DllGetClassObject=dcomp10.DllGetClassObject,@1026")
#pragma comment(linker, "/EXPORT:DwmEnableMMCSS=dcomp10.DwmEnableMMCSS,@1027")
#pragma comment(linker, "/EXPORT:ord1028=dcomp10.#1028,@1028,NONAME")
#pragma comment(linker, "/EXPORT:DwmFlush=dcomp10.DwmFlush,@1029")
#pragma comment(linker, "/EXPORT:DwmpEnableDDASupport=dcomp10.DwmpEnableDDASupport,@1030")
#pragma comment(linker, "/EXPORT:ord1031=dcomp10.#1031,@1031,NONAME")
#pragma comment(linker, "/EXPORT:ord1038=dcomp10.#1038,@1038,NONAME")
#pragma comment(linker, "/EXPORT:ord1039=dcomp10.#1039,@1039,NONAME")
#pragma comment(linker, "/EXPORT:ord1040=dcomp10.#1040,@1040,NONAME")
#pragma comment(linker, "/EXPORT:ord1041=dcomp10.#1041,@1041,NONAME")
#pragma comment(linker, "/EXPORT:ord1042=dcomp10.#1042,@1042,NONAME")
#pragma comment(linker, "/EXPORT:ord1043=dcomp10.#1043,@1043,NONAME")
#pragma comment(linker, "/EXPORT:ord1044=dcomp10.#1044,@1044,NONAME")
#pragma comment(linker, "/EXPORT:ord1045=dcomp10.#1045,@1045,NONAME")
#pragma comment(linker, "/EXPORT:ord1046=dcomp10.#1046,@1046,NONAME")
#pragma comment(linker, "/EXPORT:ord1047=dcomp10.#1047,@1047,NONAME")
#pragma comment(linker, "/EXPORT:ord1048=dcomp10.#1048,@1048,NONAME")
#pragma comment(linker, "/EXPORT:ord2000=dcomp10.#2000,@2000,NONAME")
#pragma comment(linker, "/EXPORT:ord2001=dcomp10.#2001,@2001,NONAME")
#pragma comment(linker, "/EXPORT:ord2002=dcomp10.#2002,@2002,NONAME")
#pragma comment(linker, "/EXPORT:ord2003=dcomp10.#2003,@2003,NONAME")
#pragma comment(linker, "/EXPORT:ord2004=dcomp10.#2004,@2004,NONAME")
#pragma comment(linker, "/EXPORT:ord2005=dcomp10.#2005,@2005,NONAME")
